name: unshelled
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  logger: ^2.0.2+1
  http: ^1.2.0
  mockito: ^5.4.4
  url_launcher: ^6.2.5
  connectivity: ^3.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  